# Settings for Bicep + post-deploy Pester example

parameters:
  - name: actionGroups
    type: object
    default: []
  - name: enableProduction
    type: boolean
    default: false
  - name: runReviewStage
    type: boolean
    default: true
  - name: drInvocation
    type: boolean
    default: false
  - name: skip_dev
    type: boolean
    default: false
  - name: skip_qa
    type: boolean
    default: false
  - name: skip_preprod
    type: boolean
    default: false

resources:
  repositories:
    - repository: PipelineDispatcher
      type: github
      endpoint: wesley-trust
      name: wesley-trust/pipeline-dispatcher
      ref: "refs/heads/main"

extends:
  template: /templates/pipeline-dispatcher.yml@PipelineDispatcher
  parameters:
    configuration:
      defaultPool:
        vmImage: "ubuntu-latest"
      serviceConnection: serviceConnection
      environments:
        - name: dev
          class: development
          #dependsOn: validation
          dependsOnSecondaryRegions: false
          primaryRegion: weu
          secondaryRegions:
            - neu
          drRegion: neu
          allowedBranches:
            - "*"
          pool:
            vmImage: "ubuntu-latest"
          skipEnvironment: ${{ parameters.skip_dev }}
          poolRegionDemand: false
        - name: qa
          class: test
          #dependsOn: validation
          dependsOnSecondaryRegions: false
          primaryRegion: weu
          allowedBranches:
            - "main"
            - "release/*"
          pool:
            vmImage: "ubuntu-latest"
          skipEnvironment: ${{ parameters.skip_qa }}
          poolRegionDemand: false
        - name: ppr
          class: acceptance
          #dependsOn: validation
          dependsOnSecondaryRegions: false
          primaryRegion: weu
          secondaryRegions:
            - neu
          allowedBranches:
            - "main"
            - "release/*"
          pool:
            vmImage: "ubuntu-latest"
          skipEnvironment: ${{ parameters.skip_preprod }}
          poolRegionDemand: false
        - name: prd
          class: production
          #dependsOn: validation
          #dependsOnSecondaryRegions: false
          primaryRegion: weu
          secondaryRegions:
            - neu
          drRegion: neu
          allowedBranches:
            - "release/*"
          pool:
            vmImage: "ubuntu-latest"
          poolRegionDemand: true
      actionGroups: ${{ parameters.actionGroups }}
      enableProduction: ${{ parameters.enableProduction }}
      runReviewStage: ${{ parameters.runReviewStage }}
      drInvocation: ${{ parameters.drInvocation }}
      variableRoot: examples/consumer/vars
      variables:
        includeCommon: true
        includeEnv: false
        includeEnvRegion: false
        includeRegionOnly: false
      variableGroups:
        - "Common-Variables"
      validation:
        enableVariableIncludes: true
      additionalRepositories:
        # - alias: Modules
      keyVault:
        name: ""
        secretsFilter: ""
